/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.Community;
import model.Doctor;
import model.DoctorDirectory;
import model.HospitalDirectory;
import model.House;
import model.PatientDirectory;

/**
 *
 * @author akshitabarot
 */
public class ADocDetails extends javax.swing.JFrame {

    /**
     * Creates new form ADocDetails
     */
    
    DoctorDirectory DocDirectory;
    HospitalDirectory HospDirectory;
    PatientDirectory PatDirectory;
    
    
    public ADocDetails() {
        initComponents();
    }

    ADocDetails(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory){
        initComponents();
        this.DocDirectory = DocDirectory;
        this.HospDirectory = HospDirectory;
        this.PatDirectory = PatDirectory;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfDocID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfFnameDoc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfLnameDoc = new javax.swing.JTextField();
        tfAgeDoc = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbGenderDoc = new javax.swing.JComboBox<>();
        dobDoc = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbDept = new javax.swing.JComboBox<>();
        tfBloodgrpDoc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfAddDoc = new javax.swing.JTextField();
        tfCityDoc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfEmailDoc = new javax.swing.JTextField();
        dojDoc = new com.toedter.calendar.JDateChooser();
        btnADSave = new javax.swing.JButton();
        btnADBack = new javax.swing.JButton();
        tfPhoneNoDoc = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfPincodeDoc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfCountryDoc = new javax.swing.JTextField();
        tfCommunityDoc = new javax.swing.JLabel();
        tfCountryDoc1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Charter", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DOCTOR'S DETAILS");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 10, 300, 50);

        jLabel6.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DOCTOR'S ID");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(520, 100, 150, 30);

        tfDocID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDocIDActionPerformed(evt);
            }
        });
        jPanel1.add(tfDocID);
        tfDocID.setBounds(720, 100, 220, 30);

        jLabel5.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FIRST NAME");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 100, 140, 30);

        tfFnameDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFnameDocActionPerformed(evt);
            }
        });
        tfFnameDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFnameDocKeyReleased(evt);
            }
        });
        jPanel1.add(tfFnameDoc);
        tfFnameDoc.setBounds(220, 100, 220, 30);

        jLabel2.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LAST NAME");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 160, 140, 30);

        jLabel10.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("AGE");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 220, 140, 30);

        tfLnameDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLnameDocActionPerformed(evt);
            }
        });
        tfLnameDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfLnameDocKeyPressed(evt);
            }
        });
        jPanel1.add(tfLnameDoc);
        tfLnameDoc.setBounds(220, 160, 220, 30);

        tfAgeDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAgeDocActionPerformed(evt);
            }
        });
        tfAgeDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfAgeDocKeyPressed(evt);
            }
        });
        jPanel1.add(tfAgeDoc);
        tfAgeDoc.setBounds(220, 220, 220, 30);

        jLabel15.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("GENDER");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 290, 140, 30);

        jLabel4.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATE OF BIRTH");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 360, 140, 30);

        cbGenderDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHERS" }));
        jPanel1.add(cbGenderDoc);
        cbGenderDoc.setBounds(220, 290, 220, 30);
        jPanel1.add(dobDoc);
        dobDoc.setBounds(220, 360, 220, 30);

        jLabel8.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DEPARTMENT");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(520, 160, 150, 30);

        jLabel11.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("BLOOD GROUP");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(520, 220, 150, 30);

        cbDept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENERAL SURGERY", "MEDICINE", "PAEDIATRICS", "ENT", "DENTAL", "GYN/OB", "CARDIOLOGY", "NEUROLOGY" }));
        jPanel1.add(cbDept);
        cbDept.setBounds(720, 160, 230, 30);

        tfBloodgrpDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBloodgrpDocActionPerformed(evt);
            }
        });
        jPanel1.add(tfBloodgrpDoc);
        tfBloodgrpDoc.setBounds(720, 220, 230, 30);

        jLabel16.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ADDRESS");
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 420, 140, 30);

        jLabel9.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CITY ");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 490, 150, 30);

        tfAddDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddDocActionPerformed(evt);
            }
        });
        jPanel1.add(tfAddDoc);
        tfAddDoc.setBounds(220, 420, 290, 30);

        tfCityDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCityDocActionPerformed(evt);
            }
        });
        jPanel1.add(tfCityDoc);
        tfCityDoc.setBounds(220, 490, 230, 30);

        jLabel12.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PHONE NUMBER");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(520, 280, 150, 30);

        jLabel13.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("EMAIL");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(520, 420, 150, 30);

        tfEmailDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailDocActionPerformed(evt);
            }
        });
        jPanel1.add(tfEmailDoc);
        tfEmailDoc.setBounds(720, 420, 230, 30);
        jPanel1.add(dojDoc);
        dojDoc.setBounds(720, 350, 230, 30);

        btnADSave.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnADSave.setForeground(new java.awt.Color(204, 0, 0));
        btnADSave.setText("SAVE");
        btnADSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnADSaveMouseClicked(evt);
            }
        });
        btnADSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnADSave);
        btnADSave.setBounds(300, 670, 130, 30);

        btnADBack.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnADBack.setForeground(new java.awt.Color(204, 0, 0));
        btnADBack.setText("BACK");
        btnADBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnADBack);
        btnADBack.setBounds(550, 670, 130, 30);

        tfPhoneNoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhoneNoDocActionPerformed(evt);
            }
        });
        tfPhoneNoDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPhoneNoDocKeyPressed(evt);
            }
        });
        jPanel1.add(tfPhoneNoDoc);
        tfPhoneNoDoc.setBounds(720, 280, 230, 30);

        jLabel17.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("PINCODE");
        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(520, 490, 150, 30);

        tfPincodeDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPincodeDocActionPerformed(evt);
            }
        });
        jPanel1.add(tfPincodeDoc);
        tfPincodeDoc.setBounds(720, 490, 220, 30);

        jLabel18.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("COUNTRY");
        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel18);
        jLabel18.setBounds(30, 550, 150, 30);

        tfCountryDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCountryDocActionPerformed(evt);
            }
        });
        jPanel1.add(tfCountryDoc);
        tfCountryDoc.setBounds(220, 550, 230, 30);

        tfCommunityDoc.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        tfCommunityDoc.setForeground(new java.awt.Color(204, 0, 0));
        tfCommunityDoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfCommunityDoc.setText("COMMUNITY");
        tfCommunityDoc.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(tfCommunityDoc);
        tfCommunityDoc.setBounds(520, 550, 150, 30);

        tfCountryDoc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCountryDoc1ActionPerformed(evt);
            }
        });
        jPanel1.add(tfCountryDoc1);
        tfCountryDoc1.setBounds(720, 550, 230, 30);

        jLabel14.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("DATE OF JOINING");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(520, 350, 150, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfDocIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDocIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDocIDActionPerformed

    private void tfFnameDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFnameDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFnameDocActionPerformed

    private void tfLnameDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLnameDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLnameDocActionPerformed

    private void tfAgeDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAgeDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAgeDocActionPerformed

    private void tfBloodgrpDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBloodgrpDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBloodgrpDocActionPerformed

    private void tfAddDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddDocActionPerformed

    private void tfCityDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCityDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCityDocActionPerformed

    private void tfEmailDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailDocActionPerformed

    private void btnADSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADSaveActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnADSaveActionPerformed

    private void btnADBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADBackActionPerformed
        // TODO add your handling code here:
        
        SysAdDoc SAD = new SysAdDoc(DocDirectory, HospDirectory, PatDirectory);
        SAD.setVisible(true);
        
    }//GEN-LAST:event_btnADBackActionPerformed

    private void tfPhoneNoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhoneNoDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneNoDocActionPerformed

    private void tfPincodeDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPincodeDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPincodeDocActionPerformed

    private void tfCountryDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCountryDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCountryDocActionPerformed

    private void btnADSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADSaveMouseClicked
        // TODO add your handling code here:
        
        
        String fname = tfFnameDoc.getText();
        String lname = tfLnameDoc.getText();
        int age = Integer.parseInt(tfAgeDoc.getText());
        String gender = cbGenderDoc.getSelectedItem().toString();
        Date dob = dobDoc.getDate();
        String add = tfAddDoc.getText();
        String city = tfCityDoc.getText();
        String country = tfCountryDoc.getText();
        String community = tfCommunityDoc.getText();
        String docID = tfDocID.getText();
        String department = cbDept.getSelectedItem().toString();
        String bloodgroup = tfBloodgrpDoc.getText();
        String phoneNo = tfPhoneNoDoc.getText();
        int length = phoneNo.length();
        Date doj = dojDoc.getDate();
        String email = tfEmailDoc.getText();
        String pincode = tfPincodeDoc.getText();
        
        
        
       
        
        
        if (gender.isEmpty() || /*dob.isEmpty() || */ fname.isEmpty() || lname.isEmpty() || /*age.isEmpty()||*/   add.isEmpty() 
                || city.isEmpty() || country.isEmpty() || docID.isEmpty() || department.isEmpty() || bloodgroup.isEmpty() || 
              /*  phoneNo.isEmpty() ||  doj.isEmpty() ||*/ email.isEmpty() || pincode.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Invalid! Kindly enter data in all fields!", 
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if (!(Pattern.matches("^[a-zA-Z0-9] +[@]{1} +[a-zA-Z0-9]+[.]{1} +[a-zA-Z0-9]+$^", email)))
                {
                    JOptionPane.showMessageDialog(null, 
                            "Kindly enter a valid Email!",
                            "Invalid!",
                            JOptionPane.ERROR_MESSAGE);
                  
            
        }
        
        else {
            Doctor dd = DocDirectory.addNewDoctor();
            dd.setfName(fname);
            dd.setlName(lname);
            dd.setDoctorID(docID);
            dd.setDepartment(department);
            //dd.setJoiningDate(doj);
            dd.setBloodgroup(bloodgroup);
            dd.setGender(gender);
            dd.setAge(age);
            dd.setPhoneNo(phoneNo);
            
            House docHouse = new House();
            docHouse.setStreetadd(add);
            dd.setHouse(docHouse);
            
            City docCity = new City();
            docCity.setCity(city);
            dd.setCity(docCity);
            
            Community docCommunity = new Community();
            docCommunity.setCommunityName(community);
            dd.setCommunity(docCommunity);
            
            Community docpincode =  new Community();
            docpincode.setPincode(pincode);
            dd.setPincode(docpincode);
            
            City docCountry = new City();
            docCountry.setCountry(country);
            dd.setCountry(docCountry);
            
            dd.setJoiningDate(doj);
            dd.setEmailAdd(email);
            
            
            JOptionPane.showMessageDialog(this, "New Record added!");
            
            tfFnameDoc.setText("");
            tfLnameDoc.setText("");
            tfAgeDoc.setText("");
            tfBloodgrpDoc.setText("");
            tfAddDoc.setText("");
            tfCityDoc.setText("");
            tfCommunityDoc.setText("");
            tfCountryDoc.setText("");
            tfDocID.setText("");
            tfEmailDoc.setText("");
            tfPhoneNoDoc.setText("");
            tfPincodeDoc.setText("");
            cbGenderDoc.setSelectedIndex(0);
            cbDept.setSelectedIndex(0);
            
           
            
            
            
          
        }
        
    }//GEN-LAST:event_btnADSaveMouseClicked

    private void tfCountryDoc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCountryDoc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCountryDoc1ActionPerformed

    private void tfPhoneNoDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPhoneNoDocKeyPressed
        // TODO add your handling code here:
        
        try{
            String cellNumber = tfPhoneNoDoc.getText();
            int length = cellNumber.length();
            char c = evt.getKeyChar();
            
            //checks for number 0 to 9
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            ///checks if length not more than 10 digit
            if(length<10){
                tfPhoneNoDoc.setEditable(true);
                
            } else{
                tfPhoneNoDoc.setEditable(false);
            }
        }   else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                tfPhoneNoDoc.setEditable(true);
            } else{
                tfPhoneNoDoc.setEditable(false);
            }
        }
       }
       catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
    
        
    }//GEN-LAST:event_tfPhoneNoDocKeyPressed

    private void tfAgeDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAgeDocKeyPressed
        // TODO add your handling code here:
        
        String CellNumber = tfAgeDoc.getText();
        int length = CellNumber.length();
        char c = evt.getKeyChar();
        
        //check for number 0 to 1
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            //check for length not more than 2 digit
            if(length<2){
                tfAgeDoc.setEditable(true);
                
            } else{
                tfAgeDoc.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                tfAgeDoc.setEditable(true);
            } else{
                tfAgeDoc.setEditable(false);
            }
        }
    }//GEN-LAST:event_tfAgeDocKeyPressed

    private void tfFnameDocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFnameDocKeyReleased
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isWhitespace(c )|| Character.isISOControl(c)){
            tfFnameDoc.setEditable(true);
        } else {
            tfFnameDoc.setEditable(false);
        }
    }//GEN-LAST:event_tfFnameDocKeyReleased

    private void tfLnameDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLnameDocKeyPressed
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isWhitespace(c )|| Character.isISOControl(c)){
            tfLnameDoc.setEditable(true);
        } else {
            tfLnameDoc.setEditable(false);
        }
    }//GEN-LAST:event_tfLnameDocKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADocDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADocDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADocDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADocDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADocDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADBack;
    private javax.swing.JButton btnADSave;
    private javax.swing.JComboBox<String> cbDept;
    private javax.swing.JComboBox<String> cbGenderDoc;
    private com.toedter.calendar.JDateChooser dobDoc;
    private com.toedter.calendar.JDateChooser dojDoc;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfAddDoc;
    private javax.swing.JTextField tfAgeDoc;
    private javax.swing.JTextField tfBloodgrpDoc;
    private javax.swing.JTextField tfCityDoc;
    private javax.swing.JLabel tfCommunityDoc;
    private javax.swing.JTextField tfCountryDoc;
    private javax.swing.JTextField tfCountryDoc1;
    private javax.swing.JTextField tfDocID;
    private javax.swing.JTextField tfEmailDoc;
    private javax.swing.JTextField tfFnameDoc;
    private javax.swing.JTextField tfLnameDoc;
    private javax.swing.JTextField tfPhoneNoDoc;
    private javax.swing.JTextField tfPincodeDoc;
    // End of variables declaration//GEN-END:variables
}
