/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.City;
import model.Community;
import model.DoctorDirectory;
import model.HospitalDirectory;
import model.House;
import model.PatientData;
import model.PatientDirectory;

/**
 *
 * @author akshitabarot
 */


public class APatientDetails extends javax.swing.JFrame {

    /**
     * Creates new form APatientDetails
     */
    
    PatientDirectory PatDirectory;
    DoctorDirectory DocDirectory;
    HospitalDirectory HospDirectory;
    
    
    public APatientDetails() {
        initComponents();
    }
    
    public APatientDetails(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory) {
        initComponents();
        //we are pushing whole reference to DoctorDirectory
        this.DocDirectory = DocDirectory;   
        this.HospDirectory = HospDirectory;
        this.PatDirectory = PatDirectory;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPatID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFnamePat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLnamePat = new javax.swing.JTextField();
        jAgePat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jGenderPat = new javax.swing.JComboBox<>();
        jDobPat = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jWeightPat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jAddressPat = new javax.swing.JTextField();
        jCityPat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jEmailPat = new javax.swing.JTextField();
        jVisitDatePat = new com.toedter.calendar.JDateChooser();
        jSaveDocButton = new javax.swing.JButton();
        jBackAddDocBtn = new javax.swing.JButton();
        jPhoneNoPat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfPincodeDoc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfCountryDoc = new javax.swing.JTextField();
        tfCommunityDoc = new javax.swing.JLabel();
        jCommunityPat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jBGroupPat = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jHeightPat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Charter", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PATIENT'S DETAILS");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 10, 300, 50);

        jLabel6.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PATIENT'S ID");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(530, 100, 150, 30);

        jPatID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatIDActionPerformed(evt);
            }
        });
        jPanel1.add(jPatID);
        jPatID.setBounds(720, 100, 230, 30);

        jLabel5.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FIRST NAME");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 100, 140, 30);

        jFnamePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFnamePatActionPerformed(evt);
            }
        });
        jFnamePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFnamePatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFnamePatKeyReleased(evt);
            }
        });
        jPanel1.add(jFnamePat);
        jFnamePat.setBounds(220, 100, 220, 30);

        jLabel2.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LAST NAME");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 160, 140, 30);

        jLabel10.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("AGE");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 220, 140, 30);

        jLnamePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLnamePatActionPerformed(evt);
            }
        });
        jLnamePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLnamePatKeyPressed(evt);
            }
        });
        jPanel1.add(jLnamePat);
        jLnamePat.setBounds(220, 160, 220, 30);

        jAgePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgePatActionPerformed(evt);
            }
        });
        jAgePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jAgePatKeyPressed(evt);
            }
        });
        jPanel1.add(jAgePat);
        jAgePat.setBounds(220, 220, 220, 30);

        jLabel15.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("GENDER");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 280, 140, 30);

        jLabel4.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATE OF BIRTH");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 340, 140, 30);

        jGenderPat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHERS" }));
        jPanel1.add(jGenderPat);
        jGenderPat.setBounds(220, 280, 220, 30);
        jPanel1.add(jDobPat);
        jDobPat.setBounds(220, 340, 220, 30);

        jLabel8.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("WEIGHT IN KGS");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(530, 220, 150, 30);

        jLabel11.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("BLOOD GROUP");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(530, 160, 150, 30);

        jWeightPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWeightPatActionPerformed(evt);
            }
        });
        jPanel1.add(jWeightPat);
        jWeightPat.setBounds(720, 220, 230, 30);

        jLabel16.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ADDRESS");
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 400, 140, 30);

        jLabel9.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CITY ");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 520, 150, 30);

        jAddressPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddressPatActionPerformed(evt);
            }
        });
        jPanel1.add(jAddressPat);
        jAddressPat.setBounds(220, 400, 290, 30);

        jCityPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCityPatActionPerformed(evt);
            }
        });
        jPanel1.add(jCityPat);
        jCityPat.setBounds(220, 520, 220, 30);

        jLabel12.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PHONE NUMBER");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(530, 460, 150, 30);

        jLabel13.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("EMAIL");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(530, 400, 150, 30);

        jEmailPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailPatActionPerformed(evt);
            }
        });
        jPanel1.add(jEmailPat);
        jEmailPat.setBounds(720, 400, 230, 30);
        jPanel1.add(jVisitDatePat);
        jVisitDatePat.setBounds(720, 340, 230, 30);

        jSaveDocButton.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jSaveDocButton.setForeground(new java.awt.Color(204, 0, 0));
        jSaveDocButton.setText("SAVE");
        jSaveDocButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSaveDocButtonMouseClicked(evt);
            }
        });
        jSaveDocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveDocButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jSaveDocButton);
        jSaveDocButton.setBounds(310, 690, 130, 30);

        jBackAddDocBtn.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jBackAddDocBtn.setForeground(new java.awt.Color(204, 0, 0));
        jBackAddDocBtn.setText("BACK");
        jBackAddDocBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackAddDocBtnActionPerformed(evt);
            }
        });
        jPanel1.add(jBackAddDocBtn);
        jBackAddDocBtn.setBounds(550, 690, 130, 30);

        jPhoneNoPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPhoneNoPatActionPerformed(evt);
            }
        });
        jPhoneNoPat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPhoneNoPatKeyPressed(evt);
            }
        });
        jPanel1.add(jPhoneNoPat);
        jPhoneNoPat.setBounds(720, 460, 230, 30);

        jLabel17.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("PINCODE");
        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(530, 520, 150, 30);

        tfPincodeDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPincodeDocActionPerformed(evt);
            }
        });
        jPanel1.add(tfPincodeDoc);
        tfPincodeDoc.setBounds(720, 520, 220, 30);

        jLabel18.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("COUNTRY");
        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel18);
        jLabel18.setBounds(30, 580, 150, 30);

        tfCountryDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCountryDocActionPerformed(evt);
            }
        });
        jPanel1.add(tfCountryDoc);
        tfCountryDoc.setBounds(220, 580, 220, 30);

        tfCommunityDoc.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        tfCommunityDoc.setForeground(new java.awt.Color(204, 0, 0));
        tfCommunityDoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfCommunityDoc.setText("COMMUNITY");
        tfCommunityDoc.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(tfCommunityDoc);
        tfCommunityDoc.setBounds(30, 460, 140, 30);

        jCommunityPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCommunityPatActionPerformed(evt);
            }
        });
        jPanel1.add(jCommunityPat);
        jCommunityPat.setBounds(220, 460, 220, 30);

        jLabel14.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("VISIT DATE");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(530, 340, 150, 30);

        jBGroupPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGroupPatActionPerformed(evt);
            }
        });
        jPanel1.add(jBGroupPat);
        jBGroupPat.setBounds(720, 160, 230, 30);

        jLabel19.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("HEIGHT IN CMS");
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel19);
        jLabel19.setBounds(530, 280, 150, 30);

        jHeightPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHeightPatActionPerformed(evt);
            }
        });
        jPanel1.add(jHeightPat);
        jHeightPat.setBounds(720, 280, 230, 30);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 990, 990);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPatIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatIDActionPerformed

    private void jFnamePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFnamePatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFnamePatActionPerformed

    private void jFnamePatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFnamePatKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jFnamePatKeyReleased

    private void jLnamePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLnamePatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLnamePatActionPerformed

    private void jLnamePatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLnamePatKeyPressed
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isWhitespace(c )|| Character.isISOControl(c)){
            jLnamePat.setEditable(true);
        } else {
            jLnamePat.setEditable(false);
        }
    }//GEN-LAST:event_jLnamePatKeyPressed

    private void jAgePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgePatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgePatActionPerformed

    private void jAgePatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAgePatKeyPressed
        // TODO add your handling code here:

        String CellNumber = jAgePat.getText();
        int length = CellNumber.length();
        char c = evt.getKeyChar();

        //check for number 0 to 1
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            //check for length not more than 2 digit
            if(length<2){
                jAgePat.setEditable(true);

            } else{
                jAgePat.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                jAgePat.setEditable(true);
            } else{
                jAgePat.setEditable(false);
            }
        }
    }//GEN-LAST:event_jAgePatKeyPressed

    private void jWeightPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWeightPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jWeightPatActionPerformed

    private void jAddressPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddressPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddressPatActionPerformed

    private void jCityPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCityPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCityPatActionPerformed

    private void jEmailPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailPatActionPerformed

    private void jSaveDocButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSaveDocButtonMouseClicked
        // TODO add your handling code here:
        
        String patID = jPatID.getText();
        String fname = jFnamePat.getText();
        String lname = jLnamePat.getText();
        int age = Integer.parseInt(jAgePat.getText());
        String gender = jGenderPat.getSelectedItem().toString();
        Date dob = jDobPat.getDate();
        String add = jAddressPat.getText();
        String city = jCityPat.getText();
        String country = tfCountryDoc.getText();
        String community = tfCommunityDoc.getText();
        Date doj = jVisitDatePat.getDate();
        //Date dob = dobDoc.getDate();
        String email = jEmailPat.getText();
        String pincode = tfPincodeDoc.getText();
        String bloodgroup = jWeightPat.getText();
        String phoneNo = jPhoneNoPat.getText();
        int length = phoneNo.length();
        double height = Double.parseDouble(jHeightPat.getText());
        double weight = Double.parseDouble(jWeightPat.getText());
        Date JoiningDate = jVisitDatePat.getDate();
        
        
        

        if (gender.isEmpty() || /*dob.isEmpty() || */ fname.isEmpty() || lname.isEmpty() || community.isEmpty() ||/*age.isEmpty()||*/   add.isEmpty()
            || city.isEmpty() || country.isEmpty() || patID.isEmpty() ||/* department.isEmpty() || */ bloodgroup.isEmpty() ||
            /*  phoneNo.isEmpty() ||  doj.isEmpty() ||*/ email.isEmpty() || pincode.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Invalid! Kindly enter data in all fields!",
                "Try Again",
                JOptionPane.ERROR_MESSAGE);
        }
        else if(length<10){
            JOptionPane.showMessageDialog(this,
                "Kindly enter cell no of 10 digits",
                "Try Again",
                JOptionPane.ERROR_MESSAGE);
        }
        
        else if (!(Pattern.matches("^[a-zA-Z0-9] +[@]{1} +[a-zA-Z0-9]+[.]{1} +[a-zA-Z0-9]+$^", email)))
        {
            JOptionPane.showMessageDialog(null,
                "Kindly enter a valid Email!",
                "Invalid!",
                JOptionPane.ERROR_MESSAGE);

        }

        else {
            PatientData pd = PatDirectory.addNewpatData();
            pd.setfName(fname);
            pd.setlName(lname);
            pd.setPatientID(patID);
            //pd.setDepartment(department);
            //pd.setJoiningDate(doj);
            pd.setBloodgroup(bloodgroup);
            pd.setGender(gender);
            pd.setAge(age);
            pd.setPhoneNo(phoneNo);
            pd.setVisitDate(JoiningDate);

            House docHouse = new House();
            docHouse.setStreetadd(add);
            pd.setHouse(docHouse);

            City docCity = new City();
            docCity.setCity(city);
            pd.setCity(docCity);

            Community docCommunity = new Community();
            docCommunity.setCommunityName(community);
            pd.setCommunity(docCommunity);

            Community docpincode =  new Community();
            docpincode.setPincode(pincode);
            pd.setPincode(docpincode);

            City docCountry = new City();
            docCountry.setCountry(country);
            pd.setCountry(docCountry);

            pd.setDateOfBirth(dob);
            pd.setVisitDate(doj);
            pd.setEmailAddress(email);

            JOptionPane.showMessageDialog(this, "New Record added!");

            jFnamePat.setText("");
            jLnamePat.setText("");
            jAgePat.setText("");
            jWeightPat.setText("");
            jAddressPat.setText("");
            jCityPat.setText("");
            tfCommunityDoc.setText("");
            tfCountryDoc.setText("");
            jPatID.setText("");
            jEmailPat.setText("");
            jPhoneNoPat.setText("");
            tfPincodeDoc.setText("");
            jGenderPat.setSelectedIndex(0);
           // cbDept.setSelectedIndex(0);

        }

    }//GEN-LAST:event_jSaveDocButtonMouseClicked

    private void jSaveDocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveDocButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jSaveDocButtonActionPerformed

    private void jBackAddDocBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackAddDocBtnActionPerformed
        // TODO add your handling code here:

        PatientDetailsAdmin PDA = new PatientDetailsAdmin(DocDirectory, HospDirectory, PatDirectory);
        PDA.setVisible(true);

    }//GEN-LAST:event_jBackAddDocBtnActionPerformed

    private void jPhoneNoPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhoneNoPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPhoneNoPatActionPerformed

    private void jPhoneNoPatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPhoneNoPatKeyPressed
        // TODO add your handling code here:

        try{
            String cellNumber = jPhoneNoPat.getText();
            int length = cellNumber.length();
            char c = evt.getKeyChar();

            //checks for number 0 to 9
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
                ///checks if length not more than 10 digit
                if(length<10){
                    jPhoneNoPat.setEditable(true);

                } else{
                    jPhoneNoPat.setEditable(false);
                }
            }   else{
                if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                    jPhoneNoPat.setEditable(true);
                } else{
                    jPhoneNoPat.setEditable(false);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_jPhoneNoPatKeyPressed

    private void tfPincodeDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPincodeDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPincodeDocActionPerformed

    private void tfCountryDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCountryDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCountryDocActionPerformed

    private void jCommunityPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCommunityPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCommunityPatActionPerformed

    private void jBGroupPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGroupPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBGroupPatActionPerformed

    private void jHeightPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHeightPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHeightPatActionPerformed

    private void jFnamePatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFnamePatKeyPressed
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isWhitespace(c )|| Character.isISOControl(c)){
            jFnamePat.setEditable(true);
        } else {
            jFnamePat.setEditable(false);
        }
        
    }//GEN-LAST:event_jFnamePatKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APatientDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAddressPat;
    private javax.swing.JTextField jAgePat;
    private javax.swing.JTextField jBGroupPat;
    private javax.swing.JButton jBackAddDocBtn;
    private javax.swing.JTextField jCityPat;
    private javax.swing.JTextField jCommunityPat;
    private com.toedter.calendar.JDateChooser jDobPat;
    private javax.swing.JTextField jEmailPat;
    private javax.swing.JTextField jFnamePat;
    private javax.swing.JComboBox<String> jGenderPat;
    private javax.swing.JTextField jHeightPat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLnamePat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPatID;
    private javax.swing.JTextField jPhoneNoPat;
    private javax.swing.JButton jSaveDocButton;
    private com.toedter.calendar.JDateChooser jVisitDatePat;
    private javax.swing.JTextField jWeightPat;
    private javax.swing.JLabel tfCommunityDoc;
    private javax.swing.JTextField tfCountryDoc;
    private javax.swing.JTextField tfPincodeDoc;
    // End of variables declaration//GEN-END:variables
}
