/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.HospitalDirectory;
import model.PatientDirectory;

/**
 *
 * @author akshitabarot
 */
public class CommunityAd extends javax.swing.JFrame {

    /**
     * Creates new form CommunityAd
     */
    
    HospitalDirectory HospDirectory;
    PatientDirectory PatDirectory;
    
    public CommunityAd() {
        initComponents();
    }

    CommunityAd(HospitalDirectory HospDirectory, PatientDirectory PatDirectory) {
         initComponents();

         this.HospDirectory = HospDirectory;
         this.PatDirectory = PatDirectory;
         
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBackDoctorDetailsAdmin = new javax.swing.JButton();
        jAssignHospBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        btnBackDoctorDetailsAdmin.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnBackDoctorDetailsAdmin.setForeground(new java.awt.Color(204, 0, 0));
        btnBackDoctorDetailsAdmin.setText("BACK");
        btnBackDoctorDetailsAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackDoctorDetailsAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackDoctorDetailsAdmin);
        btnBackDoctorDetailsAdmin.setBounds(200, 274, 90, 40);

        jAssignHospBtn.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        jAssignHospBtn.setForeground(new java.awt.Color(204, 0, 0));
        jAssignHospBtn.setText("ASSIGN HOSPITAL");
        jAssignHospBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAssignHospBtnMouseClicked(evt);
            }
        });
        jPanel1.add(jAssignHospBtn);
        jAssignHospBtn.setBounds(140, 160, 200, 50);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackDoctorDetailsAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackDoctorDetailsAdminActionPerformed
        // TODO add your handling code here:
        
        MainJFrame lp = new MainJFrame();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackDoctorDetailsAdminActionPerformed

    private void jAssignHospBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAssignHospBtnMouseClicked
        // TODO add your handling code here:
        
        CommunityAdminDetails CAD = new CommunityAdminDetails();     //Add doctor needs reference through DoctorDirectory to DocDirectory variable. DoctorDirectory needs to know the referennce in order to save the data for doctor.
        CAD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jAssignHospBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommunityAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommunityAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommunityAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommunityAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommunityAd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackDoctorDetailsAdmin;
    private javax.swing.JButton jAssignHospBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
