/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author akshitabarot
 */
public class DocFrame extends javax.swing.JFrame {

    /**
     * Creates new form DocFrame
     */
    public DocFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aptButton = new javax.swing.JButton();
        jPatDoctor = new javax.swing.JButton();
        jLogoutDoctor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        aptButton.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        aptButton.setForeground(new java.awt.Color(204, 0, 0));
        aptButton.setText("Appointments");
        jPanel1.add(aptButton);
        aptButton.setBounds(210, 160, 230, 68);

        jPatDoctor.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        jPatDoctor.setForeground(new java.awt.Color(204, 0, 0));
        jPatDoctor.setText("Patient History");
        jPatDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPatDoctorMouseClicked(evt);
            }
        });
        jPatDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatDoctorActionPerformed(evt);
            }
        });
        jPanel1.add(jPatDoctor);
        jPatDoctor.setBounds(210, 300, 230, 68);

        jLogoutDoctor.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLogoutDoctor.setForeground(new java.awt.Color(204, 0, 0));
        jLogoutDoctor.setText("LOG OUT");
        jLogoutDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogoutDoctorMouseClicked(evt);
            }
        });
        jPanel1.add(jLogoutDoctor);
        jLogoutDoctor.setBounds(250, 430, 155, 37);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPatDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatDoctorActionPerformed

    private void jPatDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPatDoctorMouseClicked
        // TODO add your handling code here:
        
        DocPatFrame dpp= new DocPatFrame();
        dpp.setVisible(true); 
        
    }//GEN-LAST:event_jPatDoctorMouseClicked

    private void jLogoutDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutDoctorMouseClicked
        // TODO add your handling code here:
        
        JFrame frame = new JFrame("Logout");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to Logout", "Logout", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            //System.exit(0);
             DocLogin dl = new DocLogin();
             dl.setVisible(true);
        }
    }//GEN-LAST:event_jLogoutDoctorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DocFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DocFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DocFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DocFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aptButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jLogoutDoctor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPatDoctor;
    // End of variables declaration//GEN-END:variables
}
