/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.DoctorDirectory;
import model.HospitalDirectory;
import model.PatientDirectory;

/**
 *
 * @author akshitabarot
 */
public class HospitalDetailsAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HospitalDetailsAdmin
     */
    
      HospitalDirectory HospDirectory;
      DoctorDirectory DocDirectory;
      PatientDirectory PatDirectory;
      
      
    public HospitalDetailsAdmin() {
        initComponents();
    }
    
    HospitalDetailsAdmin(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory) {
        initComponents();
        this.PatDirectory = PatDirectory;
        this.HospDirectory = HospDirectory;
        this.DocDirectory = DocDirectory;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jViewDocBtn = new javax.swing.JLabel();
        btnBackDoctorDetailsAdmin = new javax.swing.JButton();
        jAddDoctorButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jViewDocBtn.setFont(new java.awt.Font("Charter", 3, 18)); // NOI18N
        jViewDocBtn.setForeground(new java.awt.Color(204, 0, 0));
        jViewDocBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jViewDocBtn.setText("VIEW HOSPITAL");
        jViewDocBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jViewDocBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jViewDocBtnMouseClicked(evt);
            }
        });
        jPanel1.add(jViewDocBtn);
        jViewDocBtn.setBounds(140, 240, 200, 50);

        btnBackDoctorDetailsAdmin.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnBackDoctorDetailsAdmin.setForeground(new java.awt.Color(204, 0, 0));
        btnBackDoctorDetailsAdmin.setText("BACK");
        btnBackDoctorDetailsAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackDoctorDetailsAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackDoctorDetailsAdmin);
        btnBackDoctorDetailsAdmin.setBounds(200, 330, 90, 40);

        jAddDoctorButton.setFont(new java.awt.Font("Charter", 3, 18)); // NOI18N
        jAddDoctorButton.setForeground(new java.awt.Color(204, 0, 0));
        jAddDoctorButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAddDoctorButton.setText("ADD HOSPITAL");
        jAddDoctorButton.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jAddDoctorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddDoctorButtonMouseClicked(evt);
            }
        });
        jPanel1.add(jAddDoctorButton);
        jAddDoctorButton.setBounds(140, 150, 200, 50);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jViewDocBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jViewDocBtnMouseClicked
        // TODO add your handling code here:

        VHospDetails Vhd = new VHospDetails(DocDirectory, HospDirectory, PatDirectory);     //Add doctor needs reference through DoctorDirectory to DocDirectory variable. DoctorDirectory needs to know the referennce in order to save the data for doctor.
        Vhd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jViewDocBtnMouseClicked

    private void btnBackDoctorDetailsAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackDoctorDetailsAdminActionPerformed
        // TODO add your handling code here:

        SysAdFrame SA = new SysAdFrame(DocDirectory, HospDirectory, PatDirectory);
        SA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackDoctorDetailsAdminActionPerformed

    private void jAddDoctorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddDoctorButtonMouseClicked
        // TODO add your handling code here:
        
        AHospDetails Ahd = new AHospDetails(DocDirectory, HospDirectory, PatDirectory);     //Add doctor needs reference through DoctorDirectory to DocDirectory variable. DoctorDirectory needs to know the referennce in order to save the data for doctor.
        Ahd.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jAddDoctorButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalDetailsAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackDoctorDetailsAdmin;
    private javax.swing.JLabel jAddDoctorButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jViewDocBtn;
    // End of variables declaration//GEN-END:variables
}
