/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.DocModel;
import model.EncounterHistory;

/**
 *
 * @author akshitabarot
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    DocModel docModel;
    EncounterHistory encounterHistory;
    
    public MainJFrame() {
        initComponents();
        
        //encounterHistory = new EncounterHistory();
    }
    public MainJFrame(DocModel docModel) {
        initComponents();
   
        this.docModel = docModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        communityAdminBtn = new javax.swing.JButton();
        hospitalAdminBtn = new javax.swing.JButton();
        doctorsBtn = new javax.swing.JButton();
        systemAdminBtn = new javax.swing.JButton();
        patientsBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        jPanel1.setLayout(null);

        communityAdminBtn.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        communityAdminBtn.setForeground(new java.awt.Color(204, 0, 0));
        communityAdminBtn.setText("Community Admin");
        communityAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityAdminBtnActionPerformed(evt);
            }
        });
        jPanel1.add(communityAdminBtn);
        communityAdminBtn.setBounds(210, 580, 190, 54);

        hospitalAdminBtn.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        hospitalAdminBtn.setForeground(new java.awt.Color(204, 0, 0));
        hospitalAdminBtn.setText("Hospital Admin");
        hospitalAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalAdminBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hospitalAdminBtn);
        hospitalAdminBtn.setBounds(420, 580, 180, 54);

        doctorsBtn.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        doctorsBtn.setForeground(new java.awt.Color(204, 0, 0));
        doctorsBtn.setText("Doctors");
        doctorsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(doctorsBtn);
        doctorsBtn.setBounds(620, 580, 180, 50);

        systemAdminBtn.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        systemAdminBtn.setForeground(new java.awt.Color(204, 0, 0));
        systemAdminBtn.setText("System Admin");
        systemAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemAdminBtnActionPerformed(evt);
            }
        });
        jPanel1.add(systemAdminBtn);
        systemAdminBtn.setBounds(20, 580, 168, 54);

        patientsBtn.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        patientsBtn.setForeground(new java.awt.Color(204, 0, 0));
        patientsBtn.setText("Patients");
        patientsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(patientsBtn);
        patientsBtn.setBounds(820, 580, 168, 54);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 410, 150, 130);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 410, 150, 130);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(830, 420, 150, 130);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(630, 420, 150, 130);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 400, 150, 130);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 220, 280, 60);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 990, 970);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void communityAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityAdminBtnActionPerformed
        // TODO add your handling code here:
        CommunityAd CA = new CommunityAd();
        CA.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_communityAdminBtnActionPerformed

    private void hospitalAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalAdminBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hospitalAdminBtnActionPerformed

    private void doctorsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorsBtnActionPerformed
        // TODO add your handling code here:
        DocLogin DOC = new DocLogin();
        DOC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_doctorsBtnActionPerformed

    private void systemAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemAdminBtnActionPerformed
        // TODO add your handling code here:
        SysAdLogin SAL = new SysAdLogin();
        SAL.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_systemAdminBtnActionPerformed

    private void patientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientsBtnActionPerformed
        // TODO add your handling code here:
        Patient Pat = new Patient();
        Pat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_patientsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton communityAdminBtn;
    private javax.swing.JButton doctorsBtn;
    private javax.swing.JButton hospitalAdminBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton patientsBtn;
    private javax.swing.JButton systemAdminBtn;
    // End of variables declaration//GEN-END:variables
}
