/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.EncounterHistory;

/**
 *
 * @author akshitabarot
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    EncounterHistory encounterHistory;
    
    public MainJFrame() {
        initComponents();
        
        encounterHistory = new EncounterHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCommunityAdmin = new javax.swing.JButton();
        btnHospitalAdmin = new javax.swing.JButton();
        btnDoctors = new javax.swing.JButton();
        btnSystemAdmin = new javax.swing.JButton();
        btnPatients = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        jPanel1.setLayout(null);

        btnCommunityAdmin.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnCommunityAdmin.setForeground(new java.awt.Color(204, 0, 0));
        btnCommunityAdmin.setText("Community Admin");
        btnCommunityAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunityAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnCommunityAdmin);
        btnCommunityAdmin.setBounds(209, 576, 190, 54);

        btnHospitalAdmin.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnHospitalAdmin.setForeground(new java.awt.Color(204, 0, 0));
        btnHospitalAdmin.setText("Hospital Admin");
        btnHospitalAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnHospitalAdmin);
        btnHospitalAdmin.setBounds(428, 576, 180, 54);

        btnDoctors.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnDoctors.setForeground(new java.awt.Color(204, 0, 0));
        btnDoctors.setText("Doctors");
        btnDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorsActionPerformed(evt);
            }
        });
        jPanel1.add(btnDoctors);
        btnDoctors.setBounds(660, 580, 180, 50);

        btnSystemAdmin.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnSystemAdmin.setForeground(new java.awt.Color(204, 0, 0));
        btnSystemAdmin.setText("System Admin");
        btnSystemAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSystemAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnSystemAdmin);
        btnSystemAdmin.setBounds(23, 576, 168, 54);

        btnPatients.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        btnPatients.setForeground(new java.awt.Color(204, 0, 0));
        btnPatients.setText("Patients");
        btnPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientsActionPerformed(evt);
            }
        });
        jPanel1.add(btnPatients);
        btnPatients.setBounds(880, 576, 168, 54);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 410, 150, 130);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 410, 150, 130);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(890, 420, 150, 130);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(660, 430, 150, 130);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 410, 150, 130);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 220, 280, 60);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -60, 1100, 920);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommunityAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunityAdminActionPerformed
        // TODO add your handling code here:
        CommunityAd CA = new CommunityAd();
        CA.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCommunityAdminActionPerformed

    private void btnHospitalAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHospitalAdminActionPerformed

    private void btnDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorsActionPerformed
        // TODO add your handling code here:
        DocLogin DOC = new DocLogin();
        DOC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDoctorsActionPerformed

    private void btnSystemAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemAdminActionPerformed
        // TODO add your handling code here:
        SysAdLogin SAL = new SysAdLogin();
        SAL.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btnSystemAdminActionPerformed

    private void btnPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientsActionPerformed
        // TODO add your handling code here:
        Patient PAT = new Patient();
        PAT.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPatientsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommunityAdmin;
    private javax.swing.JButton btnDoctors;
    private javax.swing.JButton btnHospitalAdmin;
    private javax.swing.JButton btnPatients;
    private javax.swing.JButton btnSystemAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
