/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.DoctorDirectory;
import model.HospitalDirectory;
import model.PatientDirectory;

/**
 *
 * @author akshitabarot
 */
public class SysAdFrame extends javax.swing.JFrame {

    /**
     * Creates new form SysAdFrame
     */
    
    DoctorDirectory DocDirectory;
    PatientDirectory PatDirectory;
    HospitalDirectory HospDirectory;
    
    
    public SysAdFrame() {
        initComponents();
        
        DocDirectory = new DoctorDirectory();
        PatDirectory  = new PatientDirectory();
        HospDirectory = new HospitalDirectory();
        
    }

    SystemAdFrame(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory) {
        initComponents();
        this.PatDirectory = PatDirectory;
        this.HospDirectory = HospDirectory;
        this.DocDirectory = DocDirectory;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jHospitalDetailsBtn = new javax.swing.JButton();
        jDoctorDetailAdminButton = new javax.swing.JButton();
        jPatientDetailsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(30000, 30000));

        jPanel1.setLayout(null);

        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 390, 180, 150);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 400, 150, 130);

        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(660, 390, 190, 150);

        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(410, 390, 190, 150);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(670, 400, 170, 120);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 400, 170, 130);

        jHospitalDetailsBtn.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        jHospitalDetailsBtn.setForeground(new java.awt.Color(204, 0, 0));
        jHospitalDetailsBtn.setText("Hospital Details");
        jHospitalDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHospitalDetailsBtnMouseClicked(evt);
            }
        });
        jHospitalDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHospitalDetailsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(jHospitalDetailsBtn);
        jHospitalDetailsBtn.setBounds(160, 560, 180, 40);

        jDoctorDetailAdminButton.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        jDoctorDetailAdminButton.setForeground(new java.awt.Color(204, 0, 0));
        jDoctorDetailAdminButton.setText("Doctor Details");
        jDoctorDetailAdminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDoctorDetailAdminButtonMouseClicked(evt);
            }
        });
        jPanel1.add(jDoctorDetailAdminButton);
        jDoctorDetailAdminButton.setBounds(420, 560, 180, 40);

        jPatientDetailsBtn.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        jPatientDetailsBtn.setForeground(new java.awt.Color(204, 0, 0));
        jPatientDetailsBtn.setText("Patient Details");
        jPatientDetailsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPatientDetailsBtnMouseClicked(evt);
            }
        });
        jPatientDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatientDetailsBtnActionPerformed(evt);
            }
        });
        jPatientDetailsBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPatientDetailsBtnKeyPressed(evt);
            }
        });
        jPanel1.add(jPatientDetailsBtn);
        jPatientDetailsBtn.setBounds(670, 560, 170, 40);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, -90, 1000, 1000);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jHospitalDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHospitalDetailsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHospitalDetailsBtnActionPerformed

    private void jPatientDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatientDetailsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatientDetailsBtnActionPerformed

    private void jDoctorDetailAdminButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDoctorDetailAdminButtonMouseClicked
        // TODO add your handling code here:
        
        DoctorDetailsAdmin DDA = new DoctorDetailsAdmin(DocDirectory, HospDirectory, PatDirectory);
        DDA.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jDoctorDetailAdminButtonMouseClicked

    private void jHospitalDetailsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHospitalDetailsBtnMouseClicked
        // TODO add your handling code here:
        
        HospitalDetailsAdmin HDA = new HospitalDetailsAdmin(DocDirectory, HospDirectory, PatDirectory);
        HDA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jHospitalDetailsBtnMouseClicked

    private void jPatientDetailsBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPatientDetailsBtnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatientDetailsBtnKeyPressed

    private void jPatientDetailsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPatientDetailsBtnMouseClicked
        // TODO add your handling code here:
        PatientDetailsAdmin PDA = new PatientDetailsAdmin(DocDirectory, HospDirectory, PatDirectory);
        PDA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPatientDetailsBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SysAdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SysAdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SysAdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SysAdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SysAdFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jDoctorDetailAdminButton;
    private javax.swing.JButton jHospitalDetailsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPatientDetailsBtn;
    // End of variables declaration//GEN-END:variables
}
