/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.City;
import model.Community;
import model.DoctorDirectory;
import model.HospitalDirectory;
import model.House;
import model.PatientData;
import model.PatientDirectory;

/**
 *
 * @author akshitabarot
 */
public class VPatDetails extends javax.swing.JFrame {

    /**
     * Creates new form VPatDetails
     */
    
       PatientDirectory PatDirectory;
       DoctorDirectory DocDirectory;
       HospitalDirectory HospDirectory;
       
       
    public VPatDetails() {
        initComponents();
    }
    
    public VPatDetails(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory) {
        initComponents();
        
          this.DocDirectory = DocDirectory;   //we are pushing whole reference to DoctorDirectory
         this.HospDirectory = HospDirectory;
         this.PatDirectory = PatDirectory; 
        
       populateTable();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPatID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFnamePat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLnamePat = new javax.swing.JTextField();
        jAgePat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jGenderPat = new javax.swing.JComboBox<>();
        jDobPat = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jWeightPat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jAddressPat = new javax.swing.JTextField();
        jCityPat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jEmailPat = new javax.swing.JTextField();
        jVisitDatePat = new com.toedter.calendar.JDateChooser();
        jViewPatButton = new javax.swing.JButton();
        jBackAddPatBtn = new javax.swing.JButton();
        jPhoneNoPat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPincodePat = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jCountryPat = new javax.swing.JTextField();
        tfCommunityDoc = new javax.swing.JLabel();
        jCommunityPat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jBGroupPat = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jHeightPat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSearchPat = new javax.swing.JTextField();
        btnDeletePat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePat = new javax.swing.JTable();
        btnUpdatePat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Charter", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PATIENT'S DETAILS");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 10, 300, 50);

        jLabel6.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PATIENT'S ID");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(530, 100, 150, 30);

        jPatID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatIDActionPerformed(evt);
            }
        });
        jPanel1.add(jPatID);
        jPatID.setBounds(720, 100, 230, 30);

        jLabel5.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FIRST NAME");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 100, 140, 30);

        jFnamePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFnamePatActionPerformed(evt);
            }
        });
        jFnamePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFnamePatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFnamePatKeyReleased(evt);
            }
        });
        jPanel1.add(jFnamePat);
        jFnamePat.setBounds(220, 100, 220, 30);

        jLabel2.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LAST NAME");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 150, 140, 30);

        jLabel10.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("AGE");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 200, 140, 30);

        jLnamePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLnamePatActionPerformed(evt);
            }
        });
        jLnamePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLnamePatKeyPressed(evt);
            }
        });
        jPanel1.add(jLnamePat);
        jLnamePat.setBounds(220, 150, 220, 30);

        jAgePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgePatActionPerformed(evt);
            }
        });
        jAgePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jAgePatKeyPressed(evt);
            }
        });
        jPanel1.add(jAgePat);
        jAgePat.setBounds(220, 200, 220, 30);

        jLabel15.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("GENDER");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 250, 140, 30);

        jLabel4.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATE OF BIRTH");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 310, 140, 30);

        jGenderPat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHERS" }));
        jPanel1.add(jGenderPat);
        jGenderPat.setBounds(220, 250, 220, 30);
        jPanel1.add(jDobPat);
        jDobPat.setBounds(220, 310, 220, 30);

        jLabel8.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("WEIGHT IN KGS");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(530, 200, 150, 30);

        jLabel11.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("BLOOD GROUP");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(530, 150, 150, 30);

        jWeightPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWeightPatActionPerformed(evt);
            }
        });
        jPanel1.add(jWeightPat);
        jWeightPat.setBounds(720, 200, 230, 30);

        jLabel16.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ADDRESS");
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 370, 140, 30);

        jLabel9.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CITY ");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 470, 150, 30);

        jAddressPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddressPatActionPerformed(evt);
            }
        });
        jPanel1.add(jAddressPat);
        jAddressPat.setBounds(220, 370, 290, 30);

        jCityPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCityPatActionPerformed(evt);
            }
        });
        jPanel1.add(jCityPat);
        jCityPat.setBounds(220, 470, 220, 30);

        jLabel12.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PHONE NUMBER");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(530, 420, 150, 30);

        jLabel13.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("EMAIL");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(530, 370, 150, 30);

        jEmailPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailPatActionPerformed(evt);
            }
        });
        jPanel1.add(jEmailPat);
        jEmailPat.setBounds(720, 370, 230, 30);
        jPanel1.add(jVisitDatePat);
        jVisitDatePat.setBounds(720, 310, 230, 30);

        jViewPatButton.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jViewPatButton.setForeground(new java.awt.Color(204, 0, 0));
        jViewPatButton.setText("VIEW");
        jViewPatButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jViewPatButtonMouseClicked(evt);
            }
        });
        jViewPatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewPatButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jViewPatButton);
        jViewPatButton.setBounds(130, 900, 130, 30);

        jBackAddPatBtn.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jBackAddPatBtn.setForeground(new java.awt.Color(204, 0, 0));
        jBackAddPatBtn.setText("BACK");
        jBackAddPatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackAddPatBtnActionPerformed(evt);
            }
        });
        jPanel1.add(jBackAddPatBtn);
        jBackAddPatBtn.setBounds(750, 900, 130, 30);

        jPhoneNoPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPhoneNoPatActionPerformed(evt);
            }
        });
        jPhoneNoPat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPhoneNoPatKeyPressed(evt);
            }
        });
        jPanel1.add(jPhoneNoPat);
        jPhoneNoPat.setBounds(720, 420, 230, 30);

        jLabel17.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("PINCODE");
        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(530, 470, 150, 30);

        jPincodePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPincodePatActionPerformed(evt);
            }
        });
        jPanel1.add(jPincodePat);
        jPincodePat.setBounds(720, 470, 220, 30);

        jLabel18.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("COUNTRY");
        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel18);
        jLabel18.setBounds(30, 520, 150, 30);

        jCountryPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCountryPatActionPerformed(evt);
            }
        });
        jPanel1.add(jCountryPat);
        jCountryPat.setBounds(220, 520, 220, 30);

        tfCommunityDoc.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        tfCommunityDoc.setForeground(new java.awt.Color(204, 0, 0));
        tfCommunityDoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfCommunityDoc.setText("COMMUNITY");
        tfCommunityDoc.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(tfCommunityDoc);
        tfCommunityDoc.setBounds(30, 420, 140, 30);

        jCommunityPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCommunityPatActionPerformed(evt);
            }
        });
        jPanel1.add(jCommunityPat);
        jCommunityPat.setBounds(220, 420, 220, 30);

        jLabel14.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("VISIT DATE");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(530, 310, 150, 30);

        jBGroupPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGroupPatActionPerformed(evt);
            }
        });
        jPanel1.add(jBGroupPat);
        jBGroupPat.setBounds(720, 150, 230, 30);

        jLabel19.setFont(new java.awt.Font("Charter", 3, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("HEIGHT IN CMS");
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel19);
        jLabel19.setBounds(530, 250, 150, 30);

        jHeightPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHeightPatActionPerformed(evt);
            }
        });
        jPanel1.add(jHeightPat);
        jHeightPat.setBounds(720, 250, 230, 30);

        jLabel7.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SEARCH");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 580, 150, 40);

        jSearchPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchPatActionPerformed(evt);
            }
        });
        jSearchPat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSearchPatKeyReleased(evt);
            }
        });
        jPanel1.add(jSearchPat);
        jSearchPat.setBounds(220, 580, 740, 40);

        btnDeletePat.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnDeletePat.setForeground(new java.awt.Color(204, 0, 0));
        btnDeletePat.setText("DELETE");
        btnDeletePat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeletePatMouseClicked(evt);
            }
        });
        btnDeletePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePatActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeletePat);
        btnDeletePat.setBounds(550, 900, 130, 30);

        jTablePat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PatID", "FName", "LName", "Age", "Gender", "DOB", "Blood Group", "Address", "Community", "Pincode", "City", "PhoneNo", "Country", "Visiting Date", "Email", "Height", "Weight"
            }
        ));
        jScrollPane1.setViewportView(jTablePat);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 650, 940, 220);

        btnUpdatePat.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnUpdatePat.setForeground(new java.awt.Color(204, 0, 0));
        btnUpdatePat.setText("UPDATE");
        btnUpdatePat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdatePatMouseClicked(evt);
            }
        });
        btnUpdatePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePatActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdatePat);
        btnUpdatePat.setBounds(350, 900, 130, 30);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 990, 990);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPatIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatIDActionPerformed

    private void jFnamePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFnamePatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFnamePatActionPerformed

    private void jFnamePatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFnamePatKeyPressed
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isWhitespace(c )|| Character.isISOControl(c)){
            jFnamePat.setEditable(true);
        } else {
            jFnamePat.setEditable(false);
        }

    }//GEN-LAST:event_jFnamePatKeyPressed

    private void jFnamePatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFnamePatKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jFnamePatKeyReleased

    private void jLnamePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLnamePatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLnamePatActionPerformed

    private void jLnamePatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLnamePatKeyPressed
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isWhitespace(c )|| Character.isISOControl(c)){
            jLnamePat.setEditable(true);
        } else {
            jLnamePat.setEditable(false);
        }
    }//GEN-LAST:event_jLnamePatKeyPressed

    private void jAgePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgePatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgePatActionPerformed

    private void jAgePatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAgePatKeyPressed
        // TODO add your handling code here:

        String CellNumber = jAgePat.getText();
        int length = CellNumber.length();
        char c = evt.getKeyChar();

        //check for number 0 to 1
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            //check for length not more than 2 digit
            if(length<2){
                jAgePat.setEditable(true);

            } else{
                jAgePat.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                jAgePat.setEditable(true);
            } else{
                jAgePat.setEditable(false);
            }
        }
    }//GEN-LAST:event_jAgePatKeyPressed

    private void jWeightPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWeightPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jWeightPatActionPerformed

    private void jAddressPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddressPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddressPatActionPerformed

    private void jCityPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCityPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCityPatActionPerformed

    private void jEmailPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailPatActionPerformed

    private void jBackAddPatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackAddPatBtnActionPerformed
        // TODO add your handling code here:

        PatientDetailsAdmin pda1 = new PatientDetailsAdmin(DocDirectory, HospDirectory,PatDirectory);
        pda1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBackAddPatBtnActionPerformed

    private void jPhoneNoPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhoneNoPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPhoneNoPatActionPerformed

    private void jPhoneNoPatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPhoneNoPatKeyPressed
        // TODO add your handling code here:

        try{
            String cellNumber = jPhoneNoPat.getText();
            int length = cellNumber.length();
            char c = evt.getKeyChar();

            //checks for number 0 to 9
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
                ///checks if length not more than 10 digit
                if(length<10){
                    jPhoneNoPat.setEditable(true);

                } else{
                    jPhoneNoPat.setEditable(false);
                }
            }   else{
                if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                    jPhoneNoPat.setEditable(true);
                } else{
                    jPhoneNoPat.setEditable(false);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jPhoneNoPatKeyPressed

    private void jPincodePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPincodePatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPincodePatActionPerformed

    private void jCountryPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCountryPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCountryPatActionPerformed

    private void jCommunityPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCommunityPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCommunityPatActionPerformed

    private void jBGroupPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGroupPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBGroupPatActionPerformed

    private void jHeightPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHeightPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHeightPatActionPerformed

    private void jSearchPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchPatActionPerformed

    private void jSearchPatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSearchPatKeyReleased
        // TODO add your handling code here:

        String search = jSearchPat.getText();
        search(search);
        
    }//GEN-LAST:event_jSearchPatKeyReleased

    private void btnDeletePatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePatMouseClicked
        // TODO add your handling code here:

        int selectedRowIndex = jTablePat.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select row to delete");
        }

        DefaultTableModel model = (DefaultTableModel) jTablePat.getModel();
        PatientData selectedPat = (PatientData) model.getValueAt(selectedRowIndex, 0);

        PatDirectory.detelePat(selectedPat);

        JOptionPane.showMessageDialog(this, "Patient Details has been deleted");

        populateTable();

        //        SysAdDoc dda1 = new SysAdDoc(DocDirectory, HospDirectory, PatDirectory);
        //        dda1.setVisible(true);
        //        this.dispose();
    }//GEN-LAST:event_btnDeletePatMouseClicked

    private void btnDeletePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePatActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnDeletePatActionPerformed

    private void btnUpdatePatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdatePatMouseClicked
        // TODO add your handling code here:

        
        DefaultTableModel model = (DefaultTableModel) jTablePat.getModel();
        if (jTablePat.getSelectedRowCount()==1){

            String patientID = jPatID.getText();
            String fname = jFnamePat.getText();
            String lname = jLnamePat.getText();
            int age = Integer.parseInt(jAgePat.getText());
            String gender = jGenderPat.getSelectedItem().toString();
            String address = jAddressPat.getText();
            String country = jCountryPat.getText();
            String community = jCommunityPat.getText();
            String bloodgroup = jBGroupPat.getText();
            String phoneNo = jPhoneNoPat.getText();
            String city = jCityPat.getText();
            Date VisitingDate = jVisitDatePat.getDate();
            Date dob = jDobPat.getDate();
            String pincode = jPincodePat.getText();
            String email = jEmailPat.getText();
            double height = Double.parseDouble(jHeightPat.getText());
            double weight = Double.parseDouble(jWeightPat.getText());
            int x= 0;
            //String image = image_txt.getText();
            //int length = cellphoneno.length();

            int length = phoneNo.length();
            if(length<10){
                JOptionPane.showMessageDialog(this,
                    "Please enter cell no of 10 digits",
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE);
                x=1;

            } else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email)))
            {
                JOptionPane.showMessageDialog(null,
                    "Please enter a valid email",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                x=1;

            } if(x!=1){
                model.setValueAt(patientID, jTablePat.getSelectedRow(),0);
                model.setValueAt(fname, jTablePat.getSelectedRow(),1);
                model.setValueAt(lname, jTablePat.getSelectedRow(),2);
                model.setValueAt(age, jTablePat.getSelectedRow(),3);
                model.setValueAt(gender, jTablePat.getSelectedRow(),4);
                model.setValueAt(dob, jTablePat.getSelectedRow(),5);
                model.setValueAt(bloodgroup, jTablePat.getSelectedRow(),5);
                model.setValueAt(address, jTablePat.getSelectedRow(),7);
                model.setValueAt(community, jTablePat.getSelectedRow(),8);
                model.setValueAt(pincode, jTablePat.getSelectedRow(),9);
                model.setValueAt(city, jTablePat.getSelectedRow(),10);
                model.setValueAt(phoneNo, jTablePat.getSelectedRow(),11);
                model.setValueAt(country, jTablePat.getSelectedRow(),12);
                model.setValueAt(VisitingDate, jTablePat.getSelectedRow(),13);
                model.setValueAt(email, jTablePat.getSelectedRow(),14);
                model.setValueAt(height, jTablePat.getSelectedRow(),15);
                model.setValueAt(weight, jTablePat.getSelectedRow(),16);

                JOptionPane.showMessageDialog(this, "Update Successfully");
            }
        }
        else if (jTablePat.getRowCount()==0){
            //if table is empty
            JOptionPane.showMessageDialog(this, "Table is empty");
        } else  {
            //if row is not selected or multiple row is selected
            JOptionPane.showMessageDialog(this, "Please select a single row for updation!");

        }

       
        
        jPatID.setText("");
        jFnamePat.setText("");
        jLnamePat.setText("");
        jAgePat.setText("");
        jBGroupPat.setText("");
        jGenderPat.setSelectedIndex(0);
        jCityPat.setText("");
        jAddressPat.setText("");
        jPhoneNoPat.setText("");
        jPincodePat.setText("");
        jEmailPat.setText("");
        jCommunityPat.setText("");
        jCountryPat.setText("");
        // JJoiningDateDoc.setDate("");
        jHeightPat.setText("");
        jWeightPat.setText("");
        

    }//GEN-LAST:event_btnUpdatePatMouseClicked

    public void search(String str){
        DefaultTableModel model = (DefaultTableModel) jTablePat.getModel();
        TableRowSorter<DefaultTableModel> trs  = new TableRowSorter<DefaultTableModel>(model);
        jTablePat.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
        
    }
    
    private void btnUpdatePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdatePatActionPerformed

    private void jViewPatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewPatButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jViewPatButtonActionPerformed

    private void jViewPatButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jViewPatButtonMouseClicked
        // TODO add your handling code here:
        
        int selectedRowIndex = jTablePat.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select row to delete");
        }

        DefaultTableModel model = (DefaultTableModel) jTablePat.getModel();
        PatientData selectedPat = (PatientData) model.getValueAt(selectedRowIndex, 0);

        jPatID.setText(String.valueOf(selectedPat.getPatientID()));  //here String.valueof is used to convert any data type like int to String.
        //JDocID.setEditable(false);

        jFnamePat.setText(String.valueOf(selectedPat.getfName()));
        //JFNameDoc.setEditable(false);

        jLnamePat.setText(String.valueOf(selectedPat.getlName()));
        //JLNameDoc.setEditable(false);

        jAgePat.setText(String.valueOf(selectedPat.getAge()));
        //JAgeDoc.setEditable(false);

        jBGroupPat.setText(String.valueOf(selectedPat.getBloodgroup()));
        //JBGroupDoc.setEditable(false);

        jGenderPat.setSelectedItem(String.valueOf(selectedPat.getGender()));
        //JGenderDoc.setEditable(false);

        House docHouse = selectedPat.getHouse();
        String stAddress = docHouse.getStreetadd();
        jAddressPat.setText(String.valueOf(stAddress));

        jPhoneNoPat.setText(String.valueOf(selectedPat.getPhoneNo()));
        //JPhoneNoDoc.setEditable(false);

        City docCity = selectedPat.getCity();
        String city = docCity.getCity();
        jCityPat.setText(String.valueOf(city));

        //JCityDoc.setText(String.valueOf(selectedDoc.getCity()));
        //JCityDoc.setEditable(false);

        jVisitDatePat.setDate(selectedPat.getVisitDate());
        // JJoiningDateDoc.setEnabled(false);

        Community docCommunity = selectedPat.getCommunity();
        String docComm = docCommunity.getCommunityName();
        jCommunityPat.setText(String.valueOf(docComm));

        Community docpincode = selectedPat.getPincode();
        String docpcode = docpincode.getPincode();
        jPincodePat.setText(String.valueOf(docpcode));

        City docCountry = selectedPat.getCountry();
        String country = docCountry.getCountry();
        jCountryPat.setText(String.valueOf(country));

        jEmailPat.setText(String.valueOf(selectedPat.getEmailAddress()));
        jHeightPat.setText(String.valueOf(selectedPat.getHeightIncms()));
        jWeightPat.setText(String.valueOf(selectedPat.getWeightInkgs()));
        
        
      
    }//GEN-LAST:event_jViewPatButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPatDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPatDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPatDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPatDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPatDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletePat;
    private javax.swing.JButton btnUpdatePat;
    private javax.swing.JTextField jAddressPat;
    private javax.swing.JTextField jAgePat;
    private javax.swing.JTextField jBGroupPat;
    private javax.swing.JButton jBackAddPatBtn;
    private javax.swing.JTextField jCityPat;
    private javax.swing.JTextField jCommunityPat;
    private javax.swing.JTextField jCountryPat;
    private com.toedter.calendar.JDateChooser jDobPat;
    private javax.swing.JTextField jEmailPat;
    private javax.swing.JTextField jFnamePat;
    private javax.swing.JComboBox<String> jGenderPat;
    private javax.swing.JTextField jHeightPat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLnamePat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPatID;
    private javax.swing.JTextField jPhoneNoPat;
    private javax.swing.JTextField jPincodePat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSearchPat;
    private javax.swing.JTable jTablePat;
    private javax.swing.JButton jViewPatButton;
    private com.toedter.calendar.JDateChooser jVisitDatePat;
    private javax.swing.JTextField jWeightPat;
    private javax.swing.JLabel tfCommunityDoc;
    // End of variables declaration//GEN-END:variables


    private void populateTable() {
        
        
        DefaultTableModel model = (DefaultTableModel) jTablePat.getModel();
        model.setRowCount(0);
        
        for(PatientData pd : PatDirectory.getPatDirectory()){
            
            Object[] row = new Object[16];
            row[0] =  pd;
            row[1] =  pd.getfName();
            row[2] =  pd.getlName();
            row[3] =  pd.getAge();
            row[4] =  pd.getGender();
            row[5] =  pd.getDateOfBirth();
            row[6] =  pd.getBloodgroup();
            
            House hd = pd.getHouse();
            row[7] =  hd.getStreetadd();
            
            Community cc = pd.getCommunity();
            row[8] = cc.getCommunityName();
            
            Community cd = pd.getPincode();
            row[9] =  cd.getPincode();
            
            City cy = pd.getCity();
            row[10] = cy.getCity();
            
            row[11] = pd.getPhoneNo();
            
            City ctry = pd.getCountry();         
            row[12] =  ctry.getCountry();
            
            row[13] = pd.getVisitDate();
            row[14] = pd.getEmailAddress();
            row[15] = pd.getHeightIncms();
            row[16] = pd.getWeightInkgs();
            
            model.addRow(row);
            
            
        }
    }
}
